---
title: "Comparação de parametros ambientais da CETSES 2019 e 2020 (Covid19). Sergio Ibarra-Espinosa, Postdoc DCA, Universidade de São Paulo"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    horizontal_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dygraphs, quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
library(data.table, quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
library(xts, quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
library(circular, quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
source("2020.R", echo = TRUE, verbose = FALSE)
```


Poluentes
===================================== 

Row
-----------------------------------------------------------------------

### O3 [μg/m³] `r paste0("Atualizado ", Sys.time())`


```{r}

# 2020
f2 <- readRDS("O3_2020.rds")
# determinando tiempo POSIXct
f2$date <- as.Date(f2$date)
ano <- year(f2$date)
month <- month(f2$date)
day <- strftime(f2$date, "%d")
f2$time <- ISOdatetime(ano, month, day, f2$hour - 1, 0, 0)

ff2 <- f2[, 
          mean(conc, na.rm = T), 
          by = .(time)]

names(ff2)[2] <- "V1_2020"

ff2$day <- strftime(ff2$time, "%a")

# 2019
f1 <- readRDS("O3_2019.rds")
# determinando tiempo POSIXct
f1$date <- as.Date(f1$date)
ano <- year(f1$date)
month <- month(f1$date)
day <- strftime(f1$date, "%d")
f1$time <- ISOdatetime(ano, month, day, f1$hour - 1, 0, 0)

ff1 <- f1[, 
        mean(conc, na.rm = T), 
        by = .(time)]

names(ff1) <- c("time_2019", "V1_2019")

ff1$day <- strftime(ff1$time, "%a")


# la idea es que se encajem (batam) 24 horas y dia de la semana, despues las fechas
# Asi se compara segunda com segunta, and so on
# produze desfase de 1 dia.
# ff2;ff1
ff <- cbind(ff2, ff1[25:(nrow(ff2) + 24)])

# Como 2020 tem 29 de fev, depois o desfase sao 2 dias. Porem
#          time V1_2020 day  time_2019 V1_2019 day
# 1: 2020-02-29    15.8 sáb 2019-03-02     5.3 sáb
# ff[1417]

# 2020 tem NaN pelas horas ainda nao aconteceram
ff <- ff[!is.na(V1_2020)]

# Calcula media horaria movel
ff$media8h2020 <-  rollmean(ff$V1_2020, k = 8, fill = 0, align = "right")

ff$media8h2019 <-  rollmean(ff$V1_2019, k = 8, fill = 0, align = "right")

# Selecção maxima media horaria movel do dia
ff[, media8h2020 := max(media8h2020), by = .(strftime(time, "%Y-%m-%d"))]

ff[, media8h2019 := max(media8h2019), by = .(strftime(time, "%Y-%m-%d"))]

dif <- ff[time >= as.POSIXct("2020-03-17"), V1_2020 - V1_2019]

df <- ff[, c("V1_2020",  "V1_2019", "media8h2020", "media8h2019")]

names(df) <- c(as.character(2020:2019), "media24h2020", "media24h2019")

df$OMS8h <- 100


setDF(df)

row.names(df) <- as.character(ff$time)


dfin <- quantile(abs(dif))

dateWindow <- c("2020-03-17", as.character(Sys.Date() + 1))

presAnnotation <- function(dygraph, x, text) {
  dygraph %>%
    dyAnnotation(x, text, attachAtBottom = TRUE, width = 80)
}


dygraph(data = as.xts(df), 
        main = c("O3 [μg/m³] 2020 - 2019:\n",
                      "Max = ", round(max(dif), 2),
                      " Min = ", round(min(dif), 2),
                      " Mean = ", round(mean(dif), 2)), 
        ylab = "[μg/m³]") %>%
  dyRangeSelector(dateWindow = dateWindow) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>% 
  presAnnotation("2020-3-24", text = "Quarentena") %>% 
  presAnnotation("2020-3-17", text = "Isolamento") %>% 
  dyOptions(colors = c("green", "blue", "green", "blue", "red"))

```


### NO2 [μg/m³] `r paste0("Atualizado ", Sys.time())`

```{r}
# NO2
# 2020
f2 <- readRDS("NO2_2020.rds")
# determinando tiempo POSIXct
f2$date <- as.Date(f2$date)
ano <- year(f2$date)
month <- month(f2$date)
day <- strftime(f2$date, "%d")
f2$time <- ISOdatetime(ano, month, day, f2$hour - 1, 0, 0)

ff2 <- f2[, 
          mean(conc, na.rm = T), 
          by = .(time)]

names(ff2)[2] <- "V1_2020"

ff2$day <- strftime(ff2$time, "%a")

# 2019
f1 <- readRDS("NO2_2019.rds")
# determinando tiempo POSIXct
f1$date <- as.Date(f1$date)
ano <- year(f1$date)
month <- month(f1$date)
day <- strftime(f1$date, "%d")
f1$time <- ISOdatetime(ano, month, day, f1$hour - 1, 0, 0)

ff1 <- f1[, 
        mean(conc, na.rm = T), 
        by = .(time)]

names(ff1) <- c("time_2019", "V1_2019")

ff1$day <- strftime(ff1$time, "%a")


# la idea es que se encajem (batam) 24 horas y dia de la semana, despues las fechas
# Asi se compara segunda com segunta, and so on
# produze desfase de 1 dia.
# ff2;ff1
# con este procedimiento, los periodos terminan en dias cerradas de 24 horas
ff <- cbind(ff2, ff1[25:(nrow(ff2) + 24)])

# Como 2020 tem 29 de fev, depois o desfase sao 2 dias. Porem
#          time V1_2020 day  time_2019 V1_2019 day
# 1: 2020-02-29    15.8 sáb 2019-03-02     5.3 sáb
# ff[1417]

# 2020 tem NaN pelas horas ainda nao aconteceram
ff <- ff[!is.na(V1_2020)]

dif <- ff[time >= as.POSIXct("2020-03-17"), V1_2020 - V1_2019]

df <- ff[, c("V1_2020",  "V1_2019")]

names(df) <- as.character(2020:2019)

df$OMS1h <- 200

setDF(df)

row.names(df) <- as.character(ff$time)

dfin <- quantile(abs(dif))

presAnnotation <- function(dygraph, x, text) {
  dygraph %>%
    dyAnnotation(x, text, attachAtBottom = TRUE, width = 80)
}

dygraph(data = as.xts(df), 
        main = paste0("NO2 [μg/m³] 2020 - 2019:\n",
                      "Max = ", round(max(dif), 2),
                      " Min = ", round(min(dif), 2),
                      " Mean = ", round(mean(dif), 2)), 
        ylab = "[μg/m³]") %>%
  dyRangeSelector(dateWindow = dateWindow) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  presAnnotation("2020-3-24", text = "Quarentena") %>% 
  presAnnotation("2020-3-17", text = "Isolamento") %>% 
    dyOptions(colors = c("green", "blue", "red"))

```


Row
-----------------------------------------------------------------------

### PM2.5 [μg/m³] `r paste0("Atualizado ", Sys.time())`

```{r}
# 2020
f2 <- readRDS("MP25_2020.rds")
# determinando tiempo POSIXct
f2$date <- as.Date(f2$date)
ano <- year(f2$date)
month <- month(f2$date)
day <- strftime(f2$date, "%d")
f2$time <- ISOdatetime(ano, month, day, f2$hour - 1, 0, 0)

ff2 <- f2[, 
          mean(conc, na.rm = T), 
          by = .(time)]

names(ff2)[2] <- "V1_2020"

ff2$day <- strftime(ff2$time, "%a")

# 2019
f1 <- readRDS("MP25_2019.rds")
# determinando tiempo POSIXct
f1$date <- as.Date(f1$date)
ano <- year(f1$date)
month <- month(f1$date)
day <- strftime(f1$date, "%d")
f1$time <- ISOdatetime(ano, month, day, f1$hour - 1, 0, 0)

ff1 <- f1[, 
        mean(conc, na.rm = T), 
        by = .(time)]

names(ff1) <- c("time_2019", "V1_2019")

ff1$day <- strftime(ff1$time, "%a")


# la idea es que se encajem (batam) 24 horas y dia de la semana, despues las fechas
# Asi se compara segunda com segunta, and so on
# produze desfase de 1 dia.
# ff2;ff1
# con este procedimiento, los periodos terminan en dias cerradas de 24 horas
ff <- cbind(ff2, ff1[25:(nrow(ff2) + 24)])

# Como 2020 tem 29 de fev, depois o desfase sao 2 dias. Porem
#          time V1_2020 day  time_2019 V1_2019 day
# 1: 2020-02-29    15.8 sáb 2019-03-02     5.3 sáb
# ff[1417]

# 2020 tem NaN pelas horas ainda nao aconteceram
ff <- ff[!is.na(V1_2020)]

# Calcula media horaria movel
ff[, media24h2020 := mean(V1_2020), by = .(strftime(time, "%Y-%m-%d"))]

ff[, media24h2019 := mean(V1_2019), by = .(strftime(time, "%Y-%m-%d"))]

dif <- ff[time >= as.POSIXct("2020-03-17"), V1_2020 - V1_2019]

df <- ff[, c("V1_2020",  "V1_2019", "media24h2020", "media24h2019")]

names(df) <- c(as.character(2020:2019), "media24h2020", "media24h2019")

df$OMS24h <- 25

setDF(df)

row.names(df) <- as.character(ff$time)

dfin <- quantile(abs(dif))

presAnnotation <- function(dygraph, x, text) {
  dygraph %>%
    dyAnnotation(x, text, attachAtBottom = TRUE, width = 80)
}


dygraph(data = as.xts(df), 
        main = paste0("PM2.5 [μg/m³] 2020 - 2019:\n",
                      "Max = ", round(max(dif), 2),
                      " Min = ", round(min(dif), 2),
                      " Mean = ", round(mean(dif), 2)), 
        ylab = "[μg/m³]") %>%
  dyRangeSelector(dateWindow = dateWindow) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  presAnnotation("2020-3-24", text = "Quarentena") %>% 
  presAnnotation("2020-3-17", text = "Isolamento") %>% 
  dyOptions(colors = c("green", "blue", "green", "blue", "red"))

```

### PM10 [μg/m³] `r paste0("Atualizado ", Sys.time())`

```{r}
# 2020
f2 <- readRDS("MP10_2020.rds")
# determinando tiempo POSIXct
f2$date <- as.Date(f2$date)
ano <- year(f2$date)
month <- month(f2$date)
day <- strftime(f2$date, "%d")
f2$time <- ISOdatetime(ano, month, day, f2$hour - 1, 0, 0)

ff2 <- f2[, 
          mean(conc, na.rm = T), 
          by = .(time)]

names(ff2)[2] <- "V1_2020"

ff2$day <- strftime(ff2$time, "%a")

# 2019
f1 <- readRDS("MP10_2019.rds")
# determinando tiempo POSIXct
f1$date <- as.Date(f1$date)
ano <- year(f1$date)
month <- month(f1$date)
day <- strftime(f1$date, "%d")
f1$time <- ISOdatetime(ano, month, day, f1$hour - 1, 0, 0)

ff1 <- f1[, 
        mean(conc, na.rm = T), 
        by = .(time)]

names(ff1) <- c("time_2019", "V1_2019")

ff1$day <- strftime(ff1$time, "%a")


# la idea es que se encajem (batam) 24 horas y dia de la semana, despues las fechas
# Asi se compara segunda com segunta, and so on
# produze desfase de 1 dia.
# ff2;ff1
# con este procedimiento, los periodos terminan en dias cerradas de 24 horas
ff <- cbind(ff2, ff1[25:(nrow(ff2) + 24)])

# Como 2020 tem 29 de fev, depois o desfase sao 2 dias. Porem
#          time V1_2020 day  time_2019 V1_2019 day
# 1: 2020-02-29    15.8 sáb 2019-03-02     5.3 sáb
# ff[1417]

# 2020 tem NaN pelas horas ainda nao aconteceram
ff <- ff[!is.na(V1_2020)]

# Calcula media horaria movel
ff[, media24h2020 := mean(V1_2020), by = .(strftime(time, "%Y-%m-%d"))]

ff[, media24h2019 := mean(V1_2019), by = .(strftime(time, "%Y-%m-%d"))]

dif <- ff[time >= as.POSIXct("2020-03-17"), V1_2020 - V1_2019]

df <- ff[, c("V1_2020",  "V1_2019", "media24h2020", "media24h2019")]

names(df) <- c(as.character(2020:2019), "media24h2020", "media24h2019")

df$OMS24h <- 50

setDF(df)

row.names(df) <- as.character(ff$time)

dfin <- quantile(abs(dif))

presAnnotation <- function(dygraph, x, text) {
  dygraph %>%
    dyAnnotation(x, text, attachAtBottom = TRUE, width = 80)
}


dygraph(data = as.xts(df), 
        main = paste0("PM10 [μg/m³] 2020 - 2019:\n",
                      "Max = ", round(max(dif), 2),
                      " Min = ", round(min(dif), 2),
                      " Mean = ", round(mean(dif), 2)), 
        ylab = "[μg/m³]") %>%
  dyRangeSelector(dateWindow = dateWindow) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  presAnnotation("2020-3-24", text = "Quarentena") %>% 
  presAnnotation("2020-3-17", text = "Isolamento") %>% 
      dyOptions(colors = c("green", "blue", "green", "blue", "red"))


```


Meteorologia
===================================== 

Row
-----------------------------------------------------------------------


### WS [km/h] `r paste0("Atualizado ", Sys.time())`


```{r}
f2 <- readRDS("VV_2020.rds")
# determinando tiempo POSIXct
f2$date <- as.Date(f2$date)
ano <- year(f2$date)
month <- month(f2$date)
day <- strftime(f2$date, "%d")
f2$time <- ISOdatetime(ano, month, day, f2$hour - 1, 0, 0)

ff2 <- f2[, 
          mean(conc, na.rm = T), 
          by = .(time)]

names(ff2)[2] <- "V1_2020"

ff2$day <- strftime(ff2$time, "%a")

# 2019
f1 <- readRDS("VV_2019.rds")
# determinando tiempo POSIXct
f1$date <- as.Date(f1$date)
ano <- year(f1$date)
month <- month(f1$date)
day <- strftime(f1$date, "%d")
f1$time <- ISOdatetime(ano, month, day, f1$hour - 1, 0, 0)

ff1 <- f1[, 
        mean(conc, na.rm = T), 
        by = .(time)]

names(ff1) <- c("time_2019", "V1_2019")

ff1$day <- strftime(ff1$time, "%a")


# la idea es que se encajem (batam) 24 horas y dia de la semana, despues las fechas
# Asi se compara segunda com segunta, and so on
# produze desfase de 1 dia.
# ff2;ff1
# con este procedimiento, los periodos terminan en dias cerradas de 24 horas
ff <- cbind(ff2, ff1[25:(nrow(ff2) + 24)])

# Como 2020 tem 29 de fev, depois o desfase sao 2 dias. Porem
#          time V1_2020 day  time_2019 V1_2019 day
# 1: 2020-02-29    15.8 sáb 2019-03-02     5.3 sáb
# ff[1417]

# 2020 tem NaN pelas horas ainda nao aconteceram
ff <- ff[!is.na(V1_2020)]

dif <- ff[time >= as.POSIXct("2020-03-17"), V1_2020 - V1_2019]

df <- ff[, c("V1_2020",  "V1_2019")]

names(df) <- as.character(2020:2019)

setDF(df)

row.names(df) <- as.character(ff$time)

dfin <- quantile(abs(dif))

presAnnotation <- function(dygraph, x, text) {
  dygraph %>%
    dyAnnotation(x, text, attachAtBottom = TRUE, width = 80)
}


dygraph(data = as.xts(df), 
        main = paste0("WS [km/h] 2020 - 2019:\n",
                      "Max = ", round(max(dif), 2),
                      " Min = ", round(min(dif), 2),
                      " Mean = ", round(mean(dif), 2)), 
        ylab = "[km/h]") %>%
  dyRangeSelector(dateWindow = dateWindow) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  presAnnotation("2020-3-24", text = "Quarentena") %>% 
  presAnnotation("2020-3-17", text = "Isolamento") %>% 
    dyOptions(colors = c("green", "blue", "red"))

```


### RH [%] `r paste0("Atualizado ", Sys.time())`

```{r}
f2 <- readRDS("UR_2020.rds")
# determinando tiempo POSIXct
f2$date <- as.Date(f2$date)
ano <- year(f2$date)
month <- month(f2$date)
day <- strftime(f2$date, "%d")
f2$time <- ISOdatetime(ano, month, day, f2$hour - 1, 0, 0)

ff2 <- f2[, 
          mean(conc, na.rm = T), 
          by = .(time)]

names(ff2)[2] <- "V1_2020"

ff2$day <- strftime(ff2$time, "%a")

# 2019
f1 <- readRDS("UR_2019.rds")
# determinando tiempo POSIXct
f1$date <- as.Date(f1$date)
ano <- year(f1$date)
month <- month(f1$date)
day <- strftime(f1$date, "%d")
f1$time <- ISOdatetime(ano, month, day, f1$hour - 1, 0, 0)

ff1 <- f1[, 
        mean(conc, na.rm = T), 
        by = .(time)]

names(ff1) <- c("time_2019", "V1_2019")

ff1$day <- strftime(ff1$time, "%a")


# la idea es que se encajem (batam) 24 horas y dia de la semana, despues las fechas
# Asi se compara segunda com segunta, and so on
# produze desfase de 1 dia.
# ff2;ff1
# con este procedimiento, los periodos terminan en dias cerradas de 24 horas
ff <- cbind(ff2, ff1[25:(nrow(ff2) + 24)])

# Como 2020 tem 29 de fev, depois o desfase sao 2 dias. Porem
#          time V1_2020 day  time_2019 V1_2019 day
# 1: 2020-02-29    15.8 sáb 2019-03-02     5.3 sáb
# ff[1417]

# 2020 tem NaN pelas horas ainda nao aconteceram
ff <- ff[!is.na(V1_2020)]

dif <- ff[time >= as.POSIXct("2020-03-17"), V1_2020 - V1_2019]

df <- ff[, c("V1_2020",  "V1_2019")]

names(df) <- as.character(2020:2019)

setDF(df)

row.names(df) <- as.character(ff$time)

dfin <- quantile(abs(dif))

presAnnotation <- function(dygraph, x, text) {
  dygraph %>%
    dyAnnotation(x, text, attachAtBottom = TRUE, width = 80)
}


dygraph(data = as.xts(df), 
        main = paste0("RH [%] 2020 - 2019:\n",
                      "Max = ", round(max(dif), 2),
                      " Min = ", round(min(dif), 2),
                      " Mean = ", round(mean(dif), 2)), 
        ylab = "[%]") %>%
  dyRangeSelector(dateWindow = dateWindow) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  presAnnotation("2020-3-24", text = "Quarentena") %>% 
  presAnnotation("2020-3-17", text = "Isolamento") %>% 
    dyOptions(colors = c("green", "blue", "red"))

```

Row
-----------------------------------------------------------------------

### Direção Vento [graus] `r paste0("Atualizado ", Sys.time())`

```{r}
f2 <- readRDS("DV_2020.rds")
# determinando tiempo POSIXct
f2$date <- as.Date(f2$date)
ano <- year(f2$date)
month <- month(f2$date)
day <- strftime(f2$date, "%d")
f2$time <- ISOdatetime(ano, month, day, f2$hour - 1, 0, 0)

ff2 <- f2[!is.na(conc), 
        mean(circular::circular(conc, units = "degrees")), 
          by = .(time)]

names(ff2)[2] <- "V1_2020"

ff2$day <- strftime(ff2$time, "%a")

# 2019
f1 <- readRDS("DV_2019.rds")
# determinando tiempo POSIXct
f1$date <- as.Date(f1$date)
ano <- year(f1$date)
month <- month(f1$date)
day <- strftime(f1$date, "%d")
f1$time <- ISOdatetime(ano, month, day, f1$hour - 1, 0, 0)

ff1 <- f1[!is.na(conc), 
        mean(circular::circular(conc, units = "degrees")), 
        by = .(time)]

names(ff1) <- c("time_2019", "V1_2019")

ff1$day <- strftime(ff1$time, "%a")


# la idea es que se encajem (batam) 24 horas y dia de la semana, despues las fechas
# Asi se compara segunda com segunta, and so on
# produze desfase de 1 dia.
# ff2;ff1
# con este procedimiento, los periodos terminan en dias cerradas de 24 horas
ff <- cbind(ff2, ff1[25:(nrow(ff2) + 24)])

# Como 2020 tem 29 de fev, depois o desfase sao 2 dias. Porem
#          time V1_2020 day  time_2019 V1_2019 day
# 1: 2020-02-29    15.8 sáb 2019-03-02     5.3 sáb
# ff[1417]

# 2020 tem NaN pelas horas ainda nao aconteceram
ff <- ff[!is.na(V1_2020)]

dif <- ff[time >= as.POSIXct("2020-03-17"), V1_2020 - V1_2019]
dif <- dif[!is.na(dif)]

df <- ff[, c("V1_2020",  "V1_2019")]

names(df) <- as.character(2020:2019)

setDF(df)

row.names(df) <- as.character(ff$time)


dfin <- quantile(abs(dif))

presAnnotation <- function(dygraph, x, text) {
  dygraph %>%
    dyAnnotation(x, text, attachAtBottom = TRUE, width = 80)
}


dygraph(data = as.xts(df), 
        main = paste0("WD [°] 2020 - 2019:\n",
                      "Max = ", round(max(dif), 2),
                      " Min = ", round(min(dif), 2),
                      " Mean = ", round(mean(dif), 2)), 
        ylab = "[°]") %>%
  dyRangeSelector(dateWindow = dateWindow) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  presAnnotation("2020-3-24", text = "Quarentena") %>% 
  presAnnotation("2020-3-17", text = "Isolamento") %>% 
    dyOptions(colors = c("green", "blue", "red"))

```

### Temperatura [°C] `r paste0("Atualizado ", Sys.time())`

```{r}
# 2020 TE
f2 <- readRDS("TE_2020.rds")
# determinando tiempo POSIXct
f2$date <- as.Date(f2$date)
ano <- year(f2$date)
month <- month(f2$date)
day <- strftime(f2$date, "%d")
f2$time <- ISOdatetime(ano, month, day, f2$hour - 1, 0, 0)

ff2 <- f2[, 
          mean(conc, na.rm = T), 
          by = .(time)]

names(ff2)[2] <- "V1_2020"

ff2$day <- strftime(ff2$time, "%a")

# 2019 TE
f1 <- readRDS("TE_2019.rds")
# determinando tiempo POSIXct
f1$date <- as.Date(f1$date)
ano <- year(f1$date)
month <- month(f1$date)
day <- strftime(f1$date, "%d")
f1$time <- ISOdatetime(ano, month, day, f1$hour - 1, 0, 0)

ff1 <- f1[, 
        mean(conc, na.rm = T), 
        by = .(time)]

names(ff1) <- c("time_2019", "V1_2019")

ff1$day <- strftime(ff1$time, "%a")


# la idea es que se encajem (batam) 24 horas y dia de la semana, despues las fechas
# Asi se compara segunda com segunta, and so on
# produze desfase de 1 dia.
# ff2;ff1
# con este procedimiento, los periodos terminan en dias cerradas de 24 horas
ff <- cbind(ff2, ff1[25:(nrow(ff2) + 24)])

# Como 2020 tem 29 de fev, depois o desfase sao 2 dias. Porem
#          time V1_2020 day  time_2019 V1_2019 day
# 1: 2020-02-29    15.8 sáb 2019-03-02     5.3 sáb
# ff[1417]

# 2020 tem NaN pelas horas ainda nao aconteceram
ff <- ff[!is.na(V1_2020)]

dif <- ff[time >= as.POSIXct("2020-03-17"), V1_2020 - V1_2019]

df <- ff[, c("V1_2020",  "V1_2019")]

names(df) <- as.character(2020:2019)

setDF(df)

row.names(df) <- as.character(ff$time)

dfin <- quantile(abs(dif))

presAnnotation <- function(dygraph, x, text) {
  dygraph %>%
    dyAnnotation(x, text, attachAtBottom = TRUE, width = 80)
}


dygraph(data = as.xts(df), 
        main = paste0("Temperature [°C] 2020 - 2019:\n",
                      "Max = ", round(max(dif), 2),
                      " Min = ", round(min(dif), 2),
                      " Mean = ", round(mean(dif), 2)), 
        ylab = "[°C]") %>%
  dyRangeSelector(dateWindow = dateWindow) %>% 
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 2)) %>% 
  presAnnotation("2020-3-24", text = "Quarentena") %>% 
  presAnnotation("2020-3-17", text = "Isolamento") %>% 
    dyOptions(colors = c("green", "blue", "red"))


```




